spring:

  application:
    name: open-library

  config:
    activate:
      on-profile: test

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:open-library
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: false
        #show_sql: true
        format_sql: true
        use_sql_comments: true


server:
  port: 8080

elasticsearch:
  url: localhost
  port: 19200

preload:
  activate: true