spring:

  application:
    name: open-library

  config:
    activate:
      on-profile: demo

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:18080/openlibrary
    username: root
    password: hardpaaswordplz

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        #show_sql: true
        format_sql: true
        use_sql_comments: true



