version: '3'
services:
  open-library-mysql:
    image: mysql:8.0
    platform: linux/arm64/v8
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    container_name: open-library-mysql
    environment:
      MYSQL_DATABASE: open-library
      MYSQL_ROOT_PASSWORD: hardpaaswordplz
      MYSQL_USER: holy
      MYSQL_PASSWORD: moly
      TZ: Asia/Seoul
    ports:
      - "18080:3306"
