version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "19200:9200"
      - "19300:9300"
# docker-compose -f single-es-docker-compose.yml up -d